/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "keyvaluestore_constants.h"

namespace keyvaluestore {

const keyvaluestoreConstants g_keyvaluestore_constants;

keyvaluestoreConstants::keyvaluestoreConstants() {
}

} // namespace

