/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef keyvaluestore_CONSTANTS_H
#define keyvaluestore_CONSTANTS_H

#include "keyvaluestore_types.h"

namespace keyvaluestore {

class keyvaluestoreConstants {
 public:
  keyvaluestoreConstants();

};

extern const keyvaluestoreConstants g_keyvaluestore_constants;

} // namespace

#endif
